// include Fake lib
#r @"tools/FAKE/tools/FakeLib.dll"

open System
open System.IO
open Fake
open Fake.AssemblyInfoFile

RestorePackages()

// Directories
let buildDir  = @".\build\"
let artifactsDir = @".\artifacts\"

// Properties
let owners = "Apereo Foundation"
let copyright = "Copyright 2007-2017 Apereo.  All rights reserved."
let releaseNotes = 
    ReadFile "ReleaseNotes.md"
    |> ReleaseNotesHelper.parseReleaseNotes
let projectName = "Apereo .NET CAS Client"
let projectDir = @".\DotNetCasClient\"
let project = projectDir + "DotNetCasClient.csproj"

// Versioning related variables
let version = releaseNotes.AssemblyVersion
let buildNumber = environVarOrDefault "APPVEYOR_BUILD_NUMBER" "0"
let vcsRevision = environVarOrDefault "APPVEYOR_REPO_COMMIT" "0000000000000000000000000000000000000000"
let vcsBranchNameParam = (environVarOrDefault "APPVEYOR_REPO_BRANCH" "")
let vcsBranchName = 
    if isNullOrWhiteSpace vcsBranchNameParam then "localDeveloperMachine"
    elif (( >** ) @"^(release/).+$" vcsBranchNameParam) then "release"
    elif (( >** ) @"^(hotfix/).+$" vcsBranchNameParam) then "hotfix"
    elif (( >** ) @"^(support/).+$" vcsBranchNameParam) then "support"
    elif (( >** ) @"^(feature/).+$" vcsBranchNameParam) then vcsBranchNameParam.Replace("/", "-")
    elif vcsBranchNameParam="develop" then "develop"
    elif vcsBranchNameParam="master" then "master"
    elif vcsBranchNameParam="default" then "default"
    else invalidArg "vcsBranchName" "An unrecognized branch name was supplied."

// Set assembly version
let assemblyVersion = version + "." + buildNumber
let semanticVersion = releaseNotes.SemVer.ToString() + "." + buildNumber + "+Branch." + vcsBranchName + ".Sha." + vcsRevision
let nugetSemanticVersion = releaseNotes.SemVer.ToString()

// Targets
Target "Trace" (fun _ ->
    trace ""
    trace ("Release Notes Version: " + version)
    trace ("Release Notes Semantic Version: " + releaseNotes.SemVer.ToString())
    trace ("Build Number: " + buildNumber)
    trace ("VCS Branch Name: " + vcsBranchName)
    trace ("VCS Revision: " + vcsRevision)
    trace ("Assembly Version: " + assemblyVersion)
    trace ("Semantic Version: " + semanticVersion)
    trace ("NuGet Package Semantic Version: " + nugetSemanticVersion)
    trace ""
)

Target "Clean" (fun _ ->
    trace " --- Cleaning directories --- "

    CleanDirs [buildDir; artifactsDir]
)

Target "SetAssemblyInfo" (fun _ ->
    trace " --- Setting assembly version information --- "

    CreateCSharpAssemblyInfo (projectDir @@ "\Properties\AutoGeneratedAssemblyInfo.cs")
        [Attribute.Product projectName
         Attribute.Title projectName
         Attribute.Description ".NET client for the Apereo Central Authentication Service (CAS)"
         Attribute.Company owners
         Attribute.Copyright copyright
         Attribute.Version assemblyVersion
         Attribute.FileVersion assemblyVersion
         Attribute.InformationalVersion semanticVersion] // AKA "Product Version"
)

Target "BuildAndPackageDotNetCasClient" (fun _ -> 
    trace " --- Building DotNetCasClient project --- "
    
    // Properties
    let buildProperties =
        [
            "Optimize", "True"
            "DebugSymbols", "False"
            "DebugType", "None"
            "Configuration", "Release"
        ]

    // Build
    let projectBuildDir = buildDir @@ IO.Path.GetFileNameWithoutExtension(project)
    MSBuild projectBuildDir "Build" buildProperties [project]
    |> Log "AppBuild-Output: "

    trace " --- Fininshed building DotNetCasClient project --- "

    trace " --- Creating NuGet package --- "

    NuGet (fun p ->
        {p with
            Title = projectName
            Version = nugetSemanticVersion
            OutputPath = artifactsDir
            WorkingDir = projectBuildDir
            NoPackageAnalysis = false
            Publish = false
            Copyright = copyright
            ToolPath = @".\tools\nuget\nuget.exe"
        })
        (projectDir @@ "DotNetCasClient.nuspec")

    trace " --- Finished creating NuGet package --- "
)

// Dependencies
"Clean" 
  ==> "Trace"
  ==> "SetAssemblyInfo"
  ==> "BuildAndPackageDotNetCasClient"

// start build
RunTargetOrDefault "BuildAndPackageDotNetCasClient"