//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Apereo .NET CAS Client")]
[assembly: AssemblyDescription(".NET client for the Apereo Central Authentication Service (CAS)")]
[assembly: AssemblyCompany("Apereo Foundation")]
[assembly: AssemblyProduct("Apereo .NET CAS Client")]
[assembly: AssemblyVersion("1.2.0.0")]
[assembly: AssemblyFileVersion("1.2.0.0")]
[assembly: AssemblyInformationalVersion("1.2.0-issue-62.1+3.Branch.feature/issue-62.Sha.972152c73e26dba41cb391191f3fde1c0c8df697")]
[assembly: AssemblyCopyright("Copyright (c) 2007-2017 Apereo.  All rights reserved.")]

