//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Apereo .NET CAS Client")]
[assembly: AssemblyDescription(".NET client for the Apereo Central Authentication Service (CAS)")]
[assembly: AssemblyCompany("Apereo Foundation")]
[assembly: AssemblyProduct("Apereo .NET CAS Client")]
[assembly: AssemblyVersion("1.1.0.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("1.1.0-issue-56-1.0+Branch.feature/issue-56.Sha.613358a4094de6e5ca82166f10a38e500eb337d7")]
[assembly: AssemblyCopyright("Copyright (c) 2007-2017 Apereo.  All rights reserved.")]

