//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Apereo .NET CAS Client")]
[assembly: AssemblyDescription(".NET client for the Apereo Central Authentication Service (CAS)")]
[assembly: AssemblyCompany("Apereo Foundation")]
[assembly: AssemblyProduct("Apereo .NET CAS Client")]
[assembly: AssemblyVersion("1.1.0.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("1.1.0-issue-54-1.0+Branch.feature/issue-54.Sha.7d13e3f929603bc8e0a10db8110278d334a5cf0b")]
[assembly: AssemblyCopyright("Copyright (c) 2007-2017 Apereo.  All rights reserved.")]

